### ISSUE TITLE
gradle parameters are not working correctly.

### ISSUE THREAD

**Issue by SR-Lut3t1um** [springdoc/springdoc-openapi-gradle-plugin#17]
I use these parameters: 
`-Pdev -Pspring.datasource.url=jdbc:mysql://localhost:3306/test -Pspring.redis.host=localhost`
However they do not work.

**Comment by bnasslahsen** [comment]
@SR-Lut3t1um, 

 Your issue is not clear. The parameters you are  mentioning are not related to springdoc-openapi;
 Before submitting any issue, please make sure you have read this section (Using GitHub Issues): 
 - https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible, described in the section above.
