### ISSUE TITLE
Task with path 'generateOpenApiDocs' not found in project

### ISSUE THREAD

**Issue by SanaKanji** [springdoc/springdoc-openapi-gradle-plugin#27]
I am trying to trigger 'generateOpenApiDocs' task in my project gradle file but i am getting the error 'Task with path 'generateOpenApiDocs' not found in project'. Whereas, when i try doing the same with other gradle tasks i do not get any error. How do i trigger 'generateOpenApiDocs' in my gradle file?

PS. It works perfectly with command 'gradlew generateOpenApiDocs' in terminal or by explicitly executing the task.

**Comment by ajeans** [comment]
Same here
* `./gradlew tasks` lists correctly the `generateOpenApiDocs`
* Within `build.gradle`, `project.tasks` doesn't contain `generateOpenApiDocs`

While it is possible to depend on the task like `build.dependsOn('generateOpenApiDocs')`, it is not possible to declare an artifact cleanly as defined in https://docs.gradle.org/current/userguide/cross_project_publications.html

```java
configurations.create('openApiSpec') {
  canBeConsumed = true
}

def openApiSpecArtifact = artifacts.add('openApiSpec', openApiFile) {
  // TODO this doesn't work
  //builtBy project.tasks.findByName('generateOpenApiDocs')
  //builtBy project.tasks.generateOpenApiDocs
}
```

**Comment by MLNW** [comment]
I would like to run a task right after `generateOpenApiDocs` but I get a similar error:
```bash
org.gradle.api.UnknownTaskException: Task with name 'generateOpenApiDocs' not found in project ':backend'
```

```groovy
tasks.named('generateOpenApiDocs') {
  finalizedBy(generateApiDocsTask)
}
```

**Comment by MLNW** [comment]
@SanaKanji please let us know how you fixed this issue or reopen if you did not.

**Comment by autumnust** [comment]
Bump this thread ... Running in to the same problem and only `build.dependsOn('generateOpenApiDocs')` works for me. Other means of referring this `generateOpenApiDocs` task doesn't seem to work.

**Comment by juliaisnotavailable** [comment]
Why has this issue been closed? I am experiencing the exact same as other commenters. 
The only way I can get the task to run is either:

`build.dependsOn('generateOpenApiDocs')` From within build.gradle 
OR
`./gradlew generateOpenApiDocs` From the command line

**Comment by danielsonjh** [comment]
I think this issue is due to the `generateOpenApiDocs` task being configured in a `project.afterEvaluate` [block here](https://github.com/springdoc/springdoc-openapi-gradle-plugin/blob/4d8ea8ee2d1d62023ba94e2c1295117898aed40f/src/main/kotlin/org/springdoc/openapi/gradle/plugin/OpenApiGradlePlugin.kt#L21). Presumably because the task depends on the Spring Boot tasks being already registered?

A workaround I've found is to add the task modifications in a `project.afterEvaluate` block as well. For example, to make a single task to generate both the spec + code using the [openapi-generator-gradle-plugin](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin) you can do:
```
project.afterEvaluate {
    tasks.generateOpenApiDocs.dependsOn(tasks.clean) // The task by default does not re-run if the output file already exists
    tasks.openApiGenerate.dependsOn(tasks.generateOpenApiDocs)
}
```

This does feel hacky though, wonder if there is a way to not rely on `project.afterEvaluate`. [It doesn't seem to be recommended since it can get messy with multiple plugins anyway.](https://discuss.gradle.org/t/is-project-afterevaluate-the-proper-way-for-gradle-plugin-to-dynamically-create-default-tasks/31349/2)

**Comment by MartinAhrer** [comment]
I was wondering if it really was required to use afterEvaluate. I'm running into an issue with implementing a convention plugin that programmatically applies the springdoc-openapi plugin and adds some default configuration. 
But due to afterEvaluate it is not possible to configure the plugin in a consumer build script using the` openApi {}` block. See this discussion https://discuss.gradle.org/t/how-to-programmatically-apply-and-configure-a-plugin-and-keep-properties-set-in-the-plugin-extension/45736/3
