### ISSUE TITLE
generateOpenApiDocs uses the system JAVA_HOME variable instead of the one from gradle

### ISSUE THREAD

**Issue by Blubbaz** [springdoc/springdoc-openapi-gradle-plugin#31]
The `generateOpenApiDocs` task is currently using the `JAVA_HOME` system environment variable instead of the `org.gradle.java.home` or `System.getProperty("java.home")` property which leads to `java.lang.UnsupportedClassVersionError` in my case, because `JAVA_HOME` refers to Java8 and `org.gradle.java.home` to Java11.

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: xxx/Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

A workaround is to set the `JAVA_HOME` for the command to Java 11:
`JAVA_HOME=$JAVA11_HOME; gradle generateOpenApiDocs`

It would be nice when the `System.getProperty("java.home")` would be used instead of the system one, because this is the Java the application is also build with.

**Comment by kpramesh2212** [comment]
Yeah I think we can provide you an opition to set the java home in the plugin configuration

**Comment by christianGen** [comment]
Hi @kpramesh2212 !

There were no commits after Dec 14, 2022.

Why did you close this Issue as `completed`?

Is there already a way to specify the JVM version?

I was able to pass the version using the following hack:

```kotlin
	tasks.withType<JavaExecFork> {
		javaLauncher.set(javaToolchains.launcherFor {
			languageVersion.set(java.toolchain.languageVersion)
		})
	}
```

The problem is, that this obviously will only work for `springdoc-openapi-gralde-plugin` implementations, which use `gradle-execfork-plugin`.
