### ISSUE TITLE
customBootRun args setting not working as documented (1.4.0)

### ISSUE THREAD

**Issue by guillaume-viland** [springdoc/springdoc-openapi-gradle-plugin#87]
I am using kotlin DSL and cannot change args customBootRun as documented (at least documentation contains 2 different way to set custombootrun values no on work for me)
openApi {
    customBootRun {
        args = ["--spring.profiles.active=special"] 
    }
}

I fails with the message:
Val cannot be reassigned

Could you also give an example with 2 different args like:
"--spring.profiles.active=special"
"--spring.config.location=file:src/test/resources/"

regards

**Comment by cpoyatos1** [comment]
+1

**Comment by cpoyatos1** [comment]
Because `val` is immutable, you must set the arguments in Kotlin this way:
`args.add("--spring.profiles.active=special")`

Same for this part of the document: https://github.com/springdoc/springdoc-openapi-gradle-plugin#passing-straight-from-gradle

A solution for kotlin is:
`systemProperties.set(System.getProperties().mapKeys { it.key as String })`
