### ISSUE TITLE
Why is bootRun / a live server a requirement?

### ISSUE THREAD

**Issue by mwalkerr** [springdoc/springdoc-openapi-gradle-plugin#89]
I'm probably misunderstanding how the API spec generation works, but if I just want the "openapi.json" spec file, why do I need to run a server? Can the spec not be produced at compile time?

**Comment by sgrimm** [comment]
I believe the big reason is that applications can modify the API schema programmatically, which is needed because not all valid OpenAPI specs can be represented using annotations. Also, it's legal (and sometimes desirable on large projects) to build different parts of the application as separate jarfiles and combine them on the classpath at runtime. For example, you might have a standard set of monitoring endpoints that are shared across multiple applications. At compile time there's no way to be certain what the actual schema will be.
